version: '3.8'

services:
  inference:
    build:
      context: ./inference_service
    container_name: inference_service
    ports:
      - "8000:8000"
    env_file:
      - inference_service/.env
    restart: unless-stopped

  gateway:
    build:
      context: ./gateway
    container_name: loan_gateway
    ports:
      - "8020:8020"
    env_file:
      - gateway/.env
    depends_on:
      - inference
    restart: unless-stopped
  
  nginx:
    image: nginx:stable
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gateway
    restart: unless-stopped    
