data:
  path: "data/loan_approval_dataset.csv"

training:
  batch_size: 32
  epochs: 50
  lr: 0.001
  test_size: 0.2
  seed: 42


model:
  input_dim: 4
  output_dim: 1
  output_path: "LoanApprovalPredictor.onnx"